### ISSUE TITLE
Error "FailedToCreateRegistrationParams"

### ISSUE THREAD

**Issue by joeyisok** [ibm-bluemix-mobile-services/bms-samples-swift-helloauthentication#1]
Dear All,

During test this example code, I have got the error message "FailedToCreateRegistrationParams".
See the attachment picture below:

<img width="336" alt="screen shot 2559-09-24 at 1 22 12 pm" src="https://cloud.githubusercontent.com/assets/14802508/18806531/f7252b62-8259-11e6-9eb3-35d96ff2d840.png">

Regards,
Joey

**Comment by odedBetzalel** [comment]
Hi,
Are you using XCode 8? 
If so, you need to enable Keychain sharing. Go to you project setting, then under "capabilities" enable  "Keychain sharing"

**Comment by joeyisok** [comment]
Hi odedBetzalel,
Thank you to give the advice. After enable "Keychain sharing", app can work to connect the facebook 👍 I'm now keep going to test the app again. 

Note I'm using Xcode 8.

Regards,
Joey

**Comment by joeyisok** [comment]
It's totally work now I think :-)

<img width="200" alt="screen shot 2559-09-26 at 8 46 04 am" src="https://cloud.githubusercontent.com/assets/14802508/18820285/63163a74-83c6-11e6-8594-48b8b33409be.png">

Need to add iOS app Bundle ID in facebook app seting as well, otherwise "given url is not permitted by the application configuration ..." facebook error is gonna occur.

![screen shot 2559-09-26 at 8 48 45 am](https://cloud.githubusercontent.com/assets/14802508/18820326/d8ac2000-83c6-11e6-9aad-8815d08f8186.png)
